name: flutter_dmcb_core
description: flutter_base_kit
version: 0.0.3
homepage: https://codeup.aliyun.com/5e97f942f89c9700014a4f00/dmc-front/flutter_components/flutter_dmcb_core

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

