name: flutter_dmcb_core
description: flutter_base_kit
version: 0.0.11
homepage: https://github.com/zenganiu/flutter_dmcb_core

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:

